filebeat.inputs:
  - type: log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    paths:
      - ../bench-data/*.nljson

output.elasticsearch:
  hosts: ["http://127.0.0.1:9200"]
  bulk_max_size: 50

logging.level: info
logging.to_files: false
logging.to_stderr: true
