data_dir = "./vector"

[sources.logs]
    type = "file"
    include = ["./bench-data/*.nljson"]
    data_dir = './vector'
    fingerprinting.strategy = "device_and_inode"

[transforms.logs_parse_json]
    inputs = [ "logs" ]
    type = "remap"
    drop_on_error = false
    source = '''
    . = parse_json!(.message)
    '''

[sinks.elasticsearch]
    type = "elasticsearch"
    inputs = [ "logs" ]
    endpoint = "http://127.0.0.1:9200"
    mode = "normal"
    pipeline = "pipeline-name"
    compression = "none"
    healthcheck = false
    batch.max_bytes = 4194304  # batch.max_bytes can be changed for tuning
