pipelines:
  benchmark:
    settings:
      decoder: json
      capacity: 2048 # more capacity = more memory usage, but more throughput
    input:
      type: file
      persistence_mode: async
      watching_dir: ./bench-data/
      filename_pattern: "*.nljson"
      offsets_file: ./file.d/offsets
      offsets_op: reset
    output:
      type: elasticsearch
      endpoints:
        - http://127.0.0.1:9200
